name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test macOS
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        xcode:
          - latest
          - latest-stable
    steps:
      - name: Select toolchain
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Swift PM
        uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-${{ matrix.xcode }}-spm-v2
          restore-keys: ${{ runner.os }}-${{ matrix.xcode }}-spm-
      - name: Build & Test
        run: |
          swift test --parallel --sanitize=thread \
            -Xlinker -rpath \
            -Xlinker $(xcode-select -p)/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/macosx
